[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

[dependencies]
boolinator = "2"
cached = "0.29"
im-rc = "15"
itertools = "0.10"
lazy_static = "1.4"
md5 = "0.7"
num = "0.4"
regex = "1"
serde_json = "1"
substring = "1"
tailcall = "0.1"

[features]
